spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
        routes:
          - id: user-service
            #uri: http://localhost:8081
            uri: lb://user-service
            predicates:
              - Path=/user-service/**

          - id: vehicle-service
            uri: lb://vehicle-service
            predicates:
              - Path=/vehicle-service/**

          - id: parking-service
            uri: lb://parking-service
            predicates:
              - Path=/parking-service/**

          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/payment-service/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

