server:
  port: 8888

spring:
  application:
    name: config-server
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sassarasehan/Smart-Parking-Management-System.git
          clone-on-start: true
          default-label: main
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          search-paths: '.'
          force-pull: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/